apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    app: web
    tier: frontend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: web
    tier: frontend
---    
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  template:
    metadata:
      labels:
        app: web
        tier: frontend
    spec:
      containers:
      - name: web-frontend
        image: harshals/web:1.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: DEBUG
          value: "False"
        - name: DB_NAME
          value: mytstdb
        - name: DB_USER
          value: mypguser
        - name: DB_PASS
          value: mypassword
        - name: DB_SERVICE
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_TABLE
          value: flockertab
        ports:
        - containerPort: 8000
        command: ["/usr/local/bin/gunicorn", "-w" ,"2", "-b", ":8000", "app:app"]